### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by videodanchik** [nvidia-riva/riva-asrlib-decoder#14]
Hi @galv I think I found a memory leak in `BatchedMappedDecoderCuda`. To reproduce:
```import random
import torch
from riva.asrlib.decoder.python_decoder import (
    BatchedMappedDecoderCuda, 
    BatchedMappedDecoderCudaConfig,
)
from tqdm.auto import tqdm

config = BatchedMappedDecoderCudaConfig()
config.online_opts.decoder_opts.default_beam = 15.0
config.online_opts.decoder_opts.lattice_beam = 8.0
config.online_opts.decoder_opts.max_active = 7000
config.online_opts.determinize_lattice = False
config.online_opts.max_batch_size = 32
config.online_opts.num_channels = 64
config.online_opts.frame_shift_seconds = 0.04
config.online_opts.lattice_postprocessor_opts.acoustic_scale = 10.0

decoder = BatchedMappedDecoderCuda(
    config,
    "path_to_decoding_graph/TLG.fst",
    "path_to_decoding_words/words_riva.txt",
    500
)

for _ in tqdm(range(999999), total=999999):
    inp = torch.randn(random.randint(1, 32), random.randint(10, 200), 500).cuda()
    inp = torch.nn.functional.log_softmax(inp, dim=-1)
    
    lengths = torch.randint(1, inp.shape[1], (inp.shape[0],)).to(torch.int64)
    res = decoder.decode_mbr(inp, lengths)
```
on the first 100 iterations `nvidia-smi` gives
``` 
Fri Jan 13 22:32:50 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A10G         On   | 00000000:00:1E.0 Off |                    0 |
|  0%   20C    P0    59W / 300W |   1339MiB / 22731MiB |      0%   E. Process |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```
however after 1000 iterations 
```
Fri Jan 13 22:40:54 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A10G         On   | 00000000:00:1E.0 Off |                    0 |
|  0%   21C    P0    60W / 300W |   5383MiB / 22731MiB |     18%   E. Process |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```
Same behavior was observed for `T4` GPU for both compiled from source and installed via pip libraries.

**Comment by videodanchik** [comment]
Ok, one thing I've found is that with `config.online_opts.determinize_lattice = True` the leak disappears, but interestingly, there seems to be another leak (or maybe it is the same I don't know): each time, when I catch this type of warning during the processing:
```
WARNING ([5.5]:CheckMemoryUsage():lat/determinize-lattice-pruned.cc:320) Did not reach requested beam in determinize-lattice: size exceeds maximum 50000000 bytes; (repo,arcs,elems) = (24549120,7036192,18415752), after rebuilding, repo size was 15734304, effective beam was 5.05155 vs. requested beam 8
``` 
the occupied GPU memory increases, slowly but continuously.

BTW I set `config.online_opts.determinize_lattice = False` because it speeds up decoding significantly in my case with marginal changes in WER. With `torch.manual_seed(42)` in the code sample from my previous message, I can perform 100 iterations within 83 seconds with `config.online_opts.determinize_lattice = True` and within 39 seconds when `config.online_opts.determinize_lattice = False`. I have only 2 physical cores (4 with hyper-threading) so the lattice determinization could become a bottleneck in my setup.

**Comment by galv** [comment]
> the occupied GPU memory increases, slowly but continuously.

Just a note on this. It's likely that the gpu memory increase is probably due to the caching mechanism in cuda.

You can probably call this at the end of each loop to verify: https://pytorch.org/docs/stable/generated/torch.cuda.empty_cache.html

Regarding your other problems, they are on my mind but I unfortunately have not taken a look yet.

**Comment by galv** [comment]
You are right; there is a memory leak. I went down a red herring trying to fix the memory leak reported [here](https://github.com/kaldi-asr/kaldi/issues/4814), but there turned out to be none.

The problem is that my original support for DLPack in pybind11 was incorrect. I couldn't figure out the problem, so I just migrated to nanonbind's DLPack support, which fixes the issue. I will be pushing my fix shortly (hopefully tomorrow).

The reason why you can't immediately pinpoint this is that address sanitizer does not play well with (1) python [it reports several false positive memory leaks],(2) dynamically loaded libraries loaded into executables (this applies to native code modules loaded by python) and (3) CUDA.

**Comment by videodanchik** [comment]
Thank you @galv, I recompiled the decoder and perform the check from the above code. I don't see the increasing memory pattern anymore, closing the issue.
