### ISSUE TITLE
Intermittent Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by tarun73** [nvidia-riva/riva-asrlib-decoder#2]
I have built an FST graph on a private dataset.

While decoding works sometimes. It fails randomly with Segmentation Fault error.
We are unable to decode consistently, Can you please help regarding this?

Please let me know if you need any information regarding the setup

**Comment by messiaen** [comment]
Can you post the logs here?

@galv FYI

**Comment by tarun73** [comment]
@messiaen Mistake on our graph creation step.
We can close this.

Thanks for replying
