### ISSUE TITLE
Issue when input_deterministic is No.

### ISSUE THREAD

**Issue by yuekaizhang** [nvidia-riva/riva-asrlib-decoder#25]
`ERROR ([5.5]:CopyLaneCountersToHostSync():cudadecoder/cuda-decoder.cc:601) cudaError_t 700 : "an illegal memory access was encountered" returned from 'cudaStreamSynchronize(compute_st_)'
terminate called after throwing an instance of 'kaldi::KaldiFatalError'
  what():  kaldi::KaldiFatalError
E0420 09:15:26.919452 2480 python_be.cc:1907] Stub process is unhealthy and it will be restarted.`

People is using two different TLG.fst. Below, left TLG.fst caused the above error messages. The right works fine. The difference seems input_deterministic_attribute.

![WeChat Image_20230424135029](https://user-images.githubusercontent.com/28823245/233910379-f00384b2-e0b6-467a-9f4c-6dd9c8f5b94e.png)

However, both two TLG.fst work fine with wenet cpu runtime tlg decoding, which uses EESEN's code.

I was wondering if riva-asrlib-decoder supports TLG.fst with input_deterministc = N. Or maybe the error is caused by other reasons.

**Comment by yuekaizhang** [comment]
Closed this. It's caused by customer's mistake.

**Comment by Sshubam** [comment]
@yuekaizhang 
Hey, can you please let me know what was the cause of this error? As I am facing the same error:

[NeMo I 2024-07-17 10:59:13 collections:196] Dataset loaded with 309 files totalling 8583.33 hours
[NeMo I 2024-07-17 10:59:13 collections:197] 0 files were filtered totalling 0.00 hours
ERROR ([5.5]:CopyLaneCountersToHostSync():cudadecoder/cuda-decoder.cc:596) cudaError_t 700 : "an illegal memory access
 was encountered" returned from 'cudaStreamSynchronize(compute_st_)'
Aborted (core dumped)
