### ISSUE TITLE
git submodule third_party/kaldi did not contain bbee966746fff1a74a3924a2c7ce4a611553a47c

### ISSUE THREAD

**Issue by Invisibility** [nvidia-riva/riva-asrlib-decoder#32]
It appears that there is a missing commit to the galv/kaldi repository. Navigating from https://github.com/nvidia-riva/riva-asrlib-decoder/tree/main/third_party to the kaldi folder also failed.

**Comment by galv** [comment]
Fixed this one several months ago. Sorry for not responding earlier.
