### ISSUE TITLE
WER compare with HLG(k2) Decoder, and HLG is better

### ISSUE THREAD

**Issue by zw76859420** [nvidia-riva/riva-asrlib-decoder#34]
In our own dataset, we compared cudaFST with the HLG(k2), and the detailed results are as follows:
![image](https://github.com/nvidia-riva/riva-asrlib-decoder/assets/42910032/74adf78d-66f4-4aba-af1e-cdc55350750a)

We also test cudaFST vs HLG, and the experimental results are consistent.

**Comment by galv** [comment]
It's hard to say what's going on based on this small table. In general, I do recommend increasing default_beam and max_active if you want a lower CER: https://github.com/nvidia-riva/riva-asrlib-decoder/blob/8282368816552a7ee22c9340dce7b9c3c8d1f193/src/riva/asrlib/decoder/python_decoder.cc#L75

**Comment by galv** [comment]
I also wonder whether you are using the WFST for both decoders.

**Comment by zw76859420** [comment]
> I also wonder whether you are using the WFST for both decoders. 

Thanks for your kindly reply, we have already solved the above problem by using the same parameters. The two decoding methods are configured as follows:
1、We use the CTC with HLG decoding method in k2(zipformer based acoustic model)
2、We use the CTC with cudaFST(your project) decoing method in k2(zipformer based acoustic model)

The difference between the above two decoding methods is that k2 uses the **maximum a posterior probability** method  for decoding by default, bug cudaFST uses the **MBR** method  by default. And we fixed the default decoding method of cudaFST  in : **kaldi/src/lat/sausages.h** (MinimumBayesRiskOptions() : decode_mbr(**false**), print_silence(false))

The final WER of HLG(k2) and cudaFST is basically the same.

**Comment by zw76859420** [comment]
> It's hard to say what's going on based on this small table. In general, I do recommend increasing default_beam and max_active if you want a lower CER:
> 
> https://github.com/nvidia-riva/riva-asrlib-decoder/blob/8282368816552a7ee22c9340dce7b9c3c8d1f193/src/riva/asrlib/decoder/python_decoder.cc#L75

The decoding parameters of cudaFST  that we are using are as follows:
        int chunkSize = 50;
        float decodeBeam = 17.0f;
        float latticeBeam = 8.0f;
        int maxActive = 10000;
        boolean determinizeLattice = true;
        float frameShift = 0.03f;
        float acousticScale = 7.0f;

When we continue to increase the decodeBeam to 20.0f or icrease the maxActive to 15000, the accuracy will no longer increase， and may even decrease.
